name: "Setup Gradle"
description: "Setup Gradle"
runs:
  using: "composite"
  steps:
    # Checkout EDC code into DataSpaceConnector directory.
    - name: Checkout EDC
      uses: actions/checkout@v2
      with:
        repository: eclipse-dataspaceconnector/DataSpaceConnector
        path: DataSpaceConnector
        ref: 23c99ea20bee15703b28a4b5f50d9f66380fee45

    - name: Checkout Registration Service
      uses: actions/checkout@v2
      with:
        repository: agera-edc/RegistrationService # FIXME revert after https://github.com/agera-edc/MinimumViableDataspace/pull/178 is merged
        path: RegistrationService
        ref: 6eb3bfce1efe362b74c533fa5d9af5d460cc13b0 # FIXME update after https://github.com/agera-edc/MinimumViableDataspace/pull/178 is merged

    # Install Java and cache MVD Gradle build.
    - uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    # Cache EDC packages (installed into ~/.m2) in-between runs.
    # If the latest EDC commit ID has not changed since the last run, this will restore
    # its Maven packages from the cache.
    - name: Cache EDC packages
      uses: actions/cache@v3
      id: cache
      with:
        path: ~/.m2
        # .git/FETCH_HEAD contains latest commit ID
        key: ${{ runner.os }}-m2-${{ hashFiles('DataSpaceConnector/.git/FETCH_HEAD') }}-${{ hashFiles('RegistrationService/.git/FETCH_HEAD') }}

    # Install EDC packages into ~/.m2.
    # This action only runs if the packages could not be restored from the cache.
    - name: Build EDC packages
      run: |
        ./gradlew publishToMavenLocal -Pskip.signing
      if: steps.cache.outputs.cache-hit != 'true' # only on cache miss
      shell: bash
      working-directory: DataSpaceConnector

    - name: Delete EDC packages
      run: rm -r DataSpaceConnector
      shell: bash

    # Install Registration Service packages into ~/.m2.
    # This action only runs if the packages could not be restored from the cache.
    - name: Build Registration Service packages
      run: |
        ./gradlew publishToMavenLocal -Pskip.signing
      if: steps.cache.outputs.cache-hit != 'true' # only on cache miss
      shell: bash
      working-directory: RegistrationService

    # Keep RegistrationService sources as needed for build
    - name: Move Registration Service packages out of build directory
      run: mv RegistrationService ${{ runner.temp }}
      shell: bash
